### PR TITLE
Add Compliance Import Feature

### PR DESCRIPTION
**Pull request by michaelevans1111**
Adds DXL script and menu tree item for importing compliance fields from
excel.

### CODE REVIEW

**Comment by kayhardie** [comment]
I tested the new script using an excel to CSV template. This didn’t work well when creating the CSV on Mac as noted in the notes. I had to re-open the file in Windows, save as a new version, then use that CSV for the import and it worked fine.

**Comment by michaelevans1111** [comment]
Yay.  My guess was right as to the cause.  This is why I added a dialog at the end of the script so the user might know what to do.  Because when running it via the menu, they don’t get a chance to first see any header comments.

**Comment by kayhardie** [comment]
I tried again using the different CSV options in Mac (including MS-DOS CSV) but those still didn’t work. We will just have to do this from Windows always. Should/can we update the notes/dialog to say to make the excel/csv in Windows only?

**Comment by michaelevans1111** [comment]
I also tried those.

I don;t think it’s needed to demand that they create the file on windows.  I won’t be doing that.  I have known for years to do this trick when copying some “text” files from mac to windows.

How about if i change the comments and dialog to explain the 2 paths - csv created on windows, and csv created on a mac.

**Comment by kayhardie** [comment]
Sure, that sounds good to me. We can just say Windows is preferred, but if using Mac then blah blah blah.

**Pull request merged**
