### PR TITLE
Updated Paragraph Styles

### PR DESCRIPTION
**Pull request by kayhardie**
Line 106: Changed "Figure Caption" to "Caption"
Line 115: Changed "Table Caption" to "Caption"
Line 158: Changed "Requirement" to "Normal"

### CODE REVIEW

**Comment by michaelevans1111** [comment]
As long as everybody is aware that this will result in captions not automatically appearing in the list of figures and list of tables.  Manual procedures will be required to get them to appear, or a change to the export Word template or the exported Word file settings.

**Comment by gtrancho** [comment]
Hi Michael, 
I think there is a problem. The attributes in APS only allow for Caption and not for Figurecaption, TableCaption.Which one is the standard? May be it was a problem in APS?

Cheers
Gelys

**Comment by michaelevans1111** [comment]
Interesting.  I didn’t know that this spawned from APS. Yes, APS was the odd child.  It was not consistent with many such standards.  Since it didn’t have consistent table & caption numbering, i didn’t think it would matter - as long as it stayed outside the mainstream.

Now that you are pulling it into the fold, those factors now matter.  They need to be using the new standard, which is “Figure Caption” and “Table Caption”

I hope that helps.

Also, I submitted a merge request that Kayla can review.  It’s a tiny mod to 2 scripts that call out attributes by name - and the change is the compliance changes ( “Expected Compliance Reference” changes to “Compliance Reference” and the addition of “Compliance Reference Section or Page”).

**Comment by michaelevans1111** [comment]
I forgot to mention, the normal method of updating modules in this area, is to manually add the new enumerations to the list of enumerations for Paragraph Style.

**Comment by gtrancho** [comment]
can you remove Kayla request? and fix APS module with the correct attribute?

Gelys

**Pull request merged**
